### ISSUE TITLE
currencies are not updating at all.

### ISSUE THREAD

**Issue by memetg** [EvanRespaut/Equate#15]
It's been two days since the last update (I suppose). Forced updates by pressing "9" do not work. The app does not give any error codes or warnings. Cleared app cache, removed f-droid version and downloaded it from playstore, the problem persists. 
os: marshmallow
device: zenfone 2 ze551ml

**Comment by EvanRespaut** [comment]
Thankfully Yahoo's free API still works if I connect directly, which is
good because they could remove it at anytime haha. Probably something they
changed in the formatting, I'll check out the parsing code tonight.

**Comment by EvanRespaut** [comment]
Found the problem.  Apparently the url switched from http to https.  I'll release an update in the next day or so.

**Comment by memetg** [comment]
Thanks.
