### ISSUE TITLE
[FR] changelog

### ISSUE THREAD

**Issue by ildar** [EvanRespaut/Equate#17]
This isn't necessary but
I'm very curious what change between 1.4 and 1.5 made the code size (classes.dex) **grow 3 times**?
Looking at commits didn't give the clue

**Comment by EvanRespaut** [comment]
Oh wow didn't realize it grew that much. My guess is a few support packages
I added for the navigation drawer.

**Comment by JonnyTech** [comment]
I too am disappointed by the new file size. For me the difference is significant. Are those packages really necessary?

**Comment by EvanRespaut** [comment]
They are necessary for the navigation drawer.  I played around with optimizing a bit and was able to reduce the file size down to around 1.1MB from 1.9MB.  Still not the 400kB it used to be though.  I'll need to test this out a bit more before releasing it.  If you want to download the smaller previous version, it can be found on [f-droid](https://f-droid.org/repository/browse/?fdfilter=equate&fdid=com.llamacorp.equate).  Currency updating in the older version is broken though, so if you need that I could probably make you a 400kB apk with the fixed currency and no nav drawer.

**Comment by EvanRespaut** [comment]
I've shrunk down the app a bit since 1.5, but wasn't able to get it back to 1.4 levels because of that nav drawer.
