### ISSUE TITLE
[Feature Request] Dash price added to currencies

### ISSUE THREAD

**Issue by circledot** [EvanRespaut/Equate#18]
I would love to see the price of dash added to supported currencies. I know bitcoin is already present but dash is my primary digital currency. It would be very easy to add, here is the free API to Kraken that gives the price in USD:

https://api.kraken.com/0/public/Ticker?pair=DASHUSD

(you can also get the price of dash in euros by simply changing the pair parameter to DASHEUR)

If someone can make this happen, I would be happy to tip them. Thank you.

**Comment by circledot** [comment]
Btw, just a thought... I don't know where Equate is getting the BTC price from, but if you want to make things consistent / easier, you could modify the Kraken API by setting "pair" to XBTUSD

**Comment by EvanRespaut** [comment]
I've added Dash (along with a bunch of other cyrptocurrencies).  Updates should be live on Google Play soon, or you can get them here now.  If you would like to tip, the info can be found at the bottom of the readme file. Thanks!

**Comment by circledot** [comment]
I haven't checked it out yet but thank you very much! Am an f-droid user so I'll wait for it to be updated there, hopefully soon. Tip incoming...
