### ISSUE TITLE
Clear history

### ISSUE THREAD

**Issue by JonnyTech** [EvanRespaut/Equate#19]
Is there a way to clear all previous results?

**Comment by EvanRespaut** [comment]
Not yet, but I can add that for next release.

**Comment by imtaurus94** [comment]
I just tested the current version, wouldn't it be better if it would behave like this:

1. single tap on C: erase current line
2. double tap on C: erase history

It's just an idea.. (I personally dislike pop-up windows)

**Comment by EvanRespaut** [comment]
Yeah the popup isn't ideal, but I could see people easily accidentally clearing the history if you tap clear twice.  I suppose I could make long pressing C clear history without a popup and move the full calculator reset into the navigation window or settings area.

**Comment by JonnyTech** [comment]
Thanks, original issue is resolved.
