### ISSUE TITLE
[Feature Request] Option to disable network connectivity

### ISSUE THREAD

**Issue by twzkxkan** [EvanRespaut/Equate#2]
User requests offline mode to minimize data use/tracking

**Comment by EvanRespaut** [comment]
Thanks for the feedback!  There's actually no tracking in the app and you can avoid all data usage simply by never using the currency units. The only time an update is performed is when that currency unit tab is active.  I'll consider adding an offline mode to disable update of that in the future though.

**Comment by twzkxkan** [comment]
I appreciate the quick reply! I didn't mean to imply that you were tracking users, just the consequences of a regular Internet communication (IP address, etc).
