### ISSUE TITLE
Feature request, Missing unit

### ISSUE THREAD

**Issue by imtaurus94** [EvanRespaut/Equate#20]
Could you add in the speed units min/km ? Cause i find it's missing

**Comment by EvanRespaut** [comment]
Do you mean km/min? If so, I'll add that for next release.

**Comment by imtaurus94** [comment]
No, that wasn't a typo, i'd really need min/km. Running training plan are often based on this unit in Canada.

km/min is super easy to calculate.. but min per km is not as easy... to convert by hand. Perhaps, you could point me to the file that needs to be modified to add this unit. I'm just a beginner, but i'd like to help. Thanks

**Comment by EvanRespaut** [comment]
Ahh ok that makes sense.  Yeah that's actually super easy to add, I already had min/miles in there, so it was really just a single line to add.  I'll be added with the next commit on github (later tonight) and next release on the play store (maybe in a week or two).
