### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by suvinsnair** [EvanRespaut/Equate#21]
App crashes on my phone when **Find Unit** is clicked.
Version:1.5

**Comment by EvanRespaut** [comment]
Can you attach a stacktrace of the crash by chance?  Thanks.

**Comment by suvinsnair** [comment]
Sorry for the late response.
The Stack Trace has been attached with the same
Hope it helps.

**Comment by EvanRespaut** [comment]
I don't see the attachment, am I missing it?

**Comment by suvinsnair** [comment]
[Stack Trace.docx](https://github.com/EvanRespaut/Equate/files/1205300/Stack.Trace.docx)

**Comment by EvanRespaut** [comment]
Found the bug, it was tricky because it only appears on Kitkat and lower. I updated the code here if you want to build yourself now or just wait for the next release to the play store.

**Comment by suvinsnair** [comment]
Heyy , Works Fine 

Thanks
