### ISSUE TITLE
Explicitly state GPLv2+ license

### ISSUE THREAD

**Issue by krt16s** [EvanRespaut/Equate#3]
You have added the genereal GPLv2 license information but don't explicitly state, if you are using GPLV2 or GPLv2+ (which means "GPLv2 or any later version"). Plain GPLv2 is considered  incompatible with Apache2 license -- which is used by android support libraries.

Could you add a small note to your readme? Thanks.

**Comment by EvanRespaut** [comment]
Thanks for the input.  I updated the licence to GPLv3, should fix incompatibility issues.
