### ISSUE TITLE
Cryptocurrency rates not working

### ISSUE THREAD

**Issue by circledot** [EvanRespaut/Equate#33]
For a few days now, the cryptocurrency rates haven't been working. Any ideas why?

Actually, looking at it, I think all the rates are down.

Thanks

**Comment by EvanRespaut** [comment]
Looks like the yahoo source I've been pulling from is down: https://finance.yahoo.com/webservice/v1/symbols/allcurrencies/quote

Not sure if it's down for good or just temporary.

**Comment by circledot** [comment]
You can get the ECB rates directly. I believe it's updated once a day at 3pm:
http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml

Not sure how many currencies you get from yahoo, but a quick look at the above feed shows 32 currencies against the euro. Obviously from there you can calculate any pair.

As for cryptocurrencies, I posted it elsewhere but to save jumping around, here's the top 1000:
https://api.coinmarketcap.com/v1/ticker/?limit=1000

I suppose grabbing info from multiple sources would help in situations like this.

**Comment by tmlee** [comment]
For cryptocurrency data, I would like to suggest giving our API a shot at https://www.coingecko.com/api/docs/v3

Should be straighforward to get started and easy to consumer.

Let me know your thoughts

**Comment by EvanRespaut** [comment]
That ECB api looks pretty solid, although not nearly the same number as Yahoo. That had something like all 160 currencies plus precious metals.  If I switch to ECB, I'll should probably delete the other currencies that will always be outdated.

For crypto, I'm already using coinmarketcap, although the broken Yahoo call breaks that too, so I can fix that.

**Comment by tmlee** [comment]
Sounds good. in any case cmc will soon require api key and registration, if you are looking for a workaround that you may consider our api as an option

**Comment by CBiX** [comment]
Any decisions so far on changing the source of the exchange rates? You could also allow the user to choose from different sources, like this app does: https://github.com/hwki/SimpleBitcoinWidget
However that's not trivial to implement probably...

**Comment by circledot** [comment]
Tip incoming

**Comment by CBiX** [comment]
> Added support to pull rates from ECB. Update is live as of yesterday. Let me know if there are issues.

I was not able to build the latest master, will try again later. If it's the final 1.7 release, could you tag it and maybe upload the APK to the github releases (or attach here as .zip) until it appears on F-Droid?

**Comment by CBiX** [comment]
https://f-droid.org/wiki/page/com.llamacorp.equate/lastbuild

F-droid seems to have issues buidling 1.7, but it looks like a problem in the f-droid tools:

    FAILURE: Build failed with an exception.
    * What went wrong:
    A problem occurred configuring root project 'com.llamacorp.equate'.
    > Could not resolve all files for configuration ':classpath'.
        > Could not download gradle-core.jar (com.android.tools.build:gradle-core:2.3.3)
            > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle-core/2.3.3/gradle-core-2.3.3.jar'.
                > Connection reset
    * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    BUILD FAILED

**Comment by EvanRespaut** [comment]
I made an update that adds back in almost all currencies, sourced from here:http://www.floatrates.com/daily/usd.json  Let me know if people have issues!

**Comment by JKAbrams** [comment]
The Bitcoin price is incorrect, Equate currently reports the price at $8740 while Bitstamp has $5519.

**Comment by zuluqq** [comment]
Second this ^. 1 BTC = $3,197.67 USD in the app; it should be twice this. The BTC/ETH rates also need updating (₿0.02, not ₿0.08).

**Comment by EvanRespaut** [comment]
Yeah the currency isn't updating anymore, so it's using the last value it has. I'm guessing the free API I was using is gone or not so free anymore. I'll try to find a replacement .

**Comment by circledot** [comment]
Someone please switch this to the Coin Paprika API. It's free and reliable, I've been using it for many months:
https://api.coinpaprika.com/v1/tickers

And while you're at it, please make the top 200 coins / tokens available. If you want to make all tickers available then keep in mind some coins are using the same abbreviation. For this, simply choose the highest ranking.

Thanks

**Comment by EvanRespaut** [comment]
That API looks solid, I'll swap it over to that.

**Comment by EvanRespaut** [comment]
App is updated on play store with that new crypto source.  Give it a day or so for Google to push it out to everyone.

**Comment by circledot** [comment]
And f-droid? Thanks.

**Comment by EvanRespaut** [comment]
I tagged the project with a new version, so F-droid should update too.

**Comment by circledot** [comment]
Thanks. Post a dash address to receive a small tip.

**Comment by EvanRespaut** [comment]
Thank you!  

I actually found another small bug with the traditional currency updater, floatrates seems to reject HTTP and only accepts HTTPS so I released a new version that fixes that.  The latest version should be 2.0. This should be live on google play and f-droid shortly.
