### ISSUE TITLE
Missing currencies, update API

### ISSUE THREAD

**Issue by adrium** [EvanRespaut/Equate#36]
It seems that quite some currencies disappeared after the update to 1.7. Looking at 1d77ddc8, the reason is the switch to ECB's data which in turn was necessary because Yahoo discontinued its API.

There is a thread concerning this problem and one of the answers suggest using https://openexchangerates.org and others. See https://stackoverflow.com/a/38357848

How about implementing multiple providers with some sort of prioritizing (when a currency is referred in multiple sources).

Letting the user define a custom currency #7 is another approach and useful as well.

**Comment by EvanRespaut** [comment]
Openexchangesrates isn't a free service.  Since I don't make any money on this app right now, I would need to add ads or a paywall to cover the costs of openexchangrates.  

Letting the user define a custom currency is a good idea.

**Comment by 717g301github** [comment]
Hello,

so many people complained in East Africa as this App does not have any more Tanzanian shillings, Kenyan, Ugandan etc. 

Please make the option that each user can subscribe to openexchangerates as example.

**Comment by luiandresgonzalez** [comment]
I am also affected by this bug. I use Argentinian peso (ARS) and Brazilian Real (BRL)

**Comment by Art-2** [comment]
Hi, could it be possible to use another service?
On my computer I use [Qalculate!](https://github.com/Qalculate) wich use other sites:
https://github.com/Qalculate/libqalculate/issues/72#issuecomment-422336267

**Comment by mMuck** [comment]
And I miss the Peruvan Nuevo Sol (PEN)... :cry: 

Is [FX-Exchange](https://www.fx-exchange.com) a solution? They offer RSS feeds (example: https://www.fx-exchange.com/pen/eur.xml)
They have PEN (me), ARS, BRL https://github.com/EvanRespaut/Equate/issues/36#issuecomment-444457772, TZS, KES, UGX https://github.com/EvanRespaut/Equate/issues/36#issuecomment-442785442

Best way would be a relay server (allowed?? fair-use?) or to only load the currency which is chosen by the user (to reduce the traffic to this site). If this or a data source is not reachable, please offer the last convert rate with a possibility to change manually (custom definition). Best UX in my opinion.

Thx a lot for this great app!! :+1:

**Comment by EvanRespaut** [comment]
I forgot to close this issue last update.  All currencies should be updating successfully now, and Peruvan Nuevo Sol should be in there too. Cheers!

**Comment by mMuck** [comment]
Would not be very nice not to say THANK YOU! Late but: Very nice solved. And Peruvian Nuevo Sol works again with all the other currencies. 👍
