### ISSUE TITLE
Chain Math - BROKEN

### ISSUE THREAD

**Issue by Bug725** [EvanRespaut/Equate#39]
Example : 16.99+13.99*2=44.97!?!
🤔 should be 61.96! The more I chain the worse it is, often breaking (error). 
 This has been an issue for awhile, how long IDK. This is my favorite & only calculator I use. Please help! I can't recommend Equate anymore!

**Comment by EvanRespaut** [comment]
16.99+13.99*2 should be 44.97.  Order of operations says the 13.99*2 is done first and then 16.99 is added. If you wanted to add 16.99 and 13.99 and then multiply by 2, you need parenthesis: (16.99+13.99)*2=61.96

**Comment by ildar** [comment]
Indeed. Lol )))
