### ISSUE TITLE
[Feature request] Display result as you type

### ISSUE THREAD

**Issue by Linkinverse** [EvanRespaut/Equate#5]
Please add an option to **evaluate the expression as you type, and always display a preview of the result** (if there are no errors).
_This feature is very easy to implement and it would increase greatly the usage of the app!_

Similar calculator that does this [PC/Windows]: [http://www.pmasoft.net/englisch/pmacalc.htm](url)

> Thank you! This is the best calculator for Android!

**Comment by EvanRespaut** [comment]
Thanks for the suggestion! That feature is actually high on my todo list.  Only issue I have is exactly where to display the previewed result, while still displaying the typed expression.  One idea was perhaps put the preview in the little result list above the expression and make it red or something to signify it hasn't been permanently added to that list.  Maybe also increase the font size a bit?  Seems like a imperfect solution though.  You have any other suggestions?

**Comment by Linkinverse** [comment]
Great! I really wish i could do that myself, i tried to open the project on Android Studio but it didn't run.

I think this could be a good solution:
http://i.imgur.com/mtptPnK.png

This way the preview could be just below the input box.
What do you think?

**Comment by EvanRespaut** [comment]
Hmm that's an interesting idea.  I actually already have a (very hidden)
feature to shink down the unit conversion buttons if you hold the 8
button.  I was looking into making all of those keys a drag down type of
slider, but was having some issues with the code.  I should at least add a
little secondary icon in the upper right of the 8 to signify that feature
is there.

As for the preview, I was thinking it might make more sense for it to go
above the currently typed expression, just so when (if) equals is pressed,
the result would sort of already in the right place for the history.  Maybe
shrink in size.  I was thinking it could also be red maybe? Dunno,
something like this?
http://imgur.com/PlVle34

**Comment by Linkinverse** [comment]
Yes, above it makes more sense, i agree.

I actually have an idea:
the button "C" and "BACKSPACE" are kind of redundand and you could put them as one single button with 2 functions depending if you hold it.

See image for visual reference:
http://imgur.com/j4cyzjb

If you have problem sliding/dragging the conversion panel you could just use a Collapse/Expand button that make it "disappear".

Would this be acceptable to you?

**Comment by EvanRespaut** [comment]
Yeah that's not a bad idea, I'll look into that too.  Certainly the
backspace and delete are little redudant with the backspace hold function =
delete.

**Comment by Linkinverse** [comment]
Hi Evan,

I would like to ask... I use your app **every single day**:
is there any hope you can quickly implement the preview, and then make it "better" with time?
Even if you take one year to make it look better would be acceptable as long as somehow it works in the meanwhile.

Thank you for your support!

**Comment by EvanRespaut** [comment]
That's actually makes me really happy to hear! Do you mostly use the
regular calculator functions or also unit conversions? Also out of
curiosity, how'd you discover the app?
I think that red text preview in the history list won't be too hard to make
once get some time for it, and I was thinking of doing some coding this
weekend, so we'll see how it goes :)

**Comment by Linkinverse** [comment]
I use the mostly the regular calculator, for almost anything: work, groceries, sum bills/invoices, etc.
How i discovered it? :) Simple: I TRIED ALL THE EXISTING CALCULATORS APPS.
.....Until i found the best one.

This is exactly how i found the *PmaCalc* for windows i mentioned on the first post.
I do this all the times, some examples:
- Best free text editor: PSPad (all features from UltraEdit, but free)
- Best backup software: Areca (open source, incremental, encrypted, scheduled, split)
Etc.

...This is the curse of having a brain instead of sawdust between your ears:
you slowly transform into Nikola Tesla, while the rest of the world forget their phone/skype/email passwords and make a new account. We are surrounded by idiots.

**Comment by EvanRespaut** [comment]
Oh wow that's quite a bit of work haha.  I'll definitely have to check out
the text editor and backup software!

**Comment by EvanRespaut** [comment]
Just added support for the instant preview thingy.  Haven't pushed it to
the store because I'd want to add animations at the very least as well as
maybe a way to disable it.  You can test it out in it's current state if
you want though:

https://www.dropbox.com/s/f77ws4omjggo010/Equate_vs1.2beta.apk?dl=0

You might need to enable allow installs from non google play sources to
install it.

**Comment by Linkinverse** [comment]
**"There was a problem while parsing the package"**
_(Android 5.1.1)_

**Comment by EvanRespaut** [comment]
Have you enabled permissions for 3rd party apps?
<http://nexus5.wonderhowto.com/how-to/enable-unknown-sources-install-third-party-apps-apk-files-nexus-4-nexus-5-0150666/>
That is needed here since it's not coming directly from the store.

**Comment by Linkinverse** [comment]
Sorry, it was a problem with the downloadet i used (es file explorer).

I managed to install it now, but i still don't see any preview...it looks exactly as before..is there a hidden setting to activate this feature?

**Comment by EvanRespaut** [comment]
Ahh sorry linked the released version instead of the newest build.  Here's
the right one (you'll probably need to uninstall the current one to install
this):

https://www.dropbox.com/s/6mf5cz3p22vl6wj/Equate_vs1.2_beta.apk?dl=0

**Comment by Linkinverse** [comment]
This is too good to be true: it works perfectly!

**Comment by Linkinverse** [comment]
**Thank you**, this feature is awesome!

**Comment by EvanRespaut** [comment]
Haha you're welcome, glad you like it!

**Comment by Linkinverse** [comment]
I just suggested your app to all my geek friends.
Closing this issue, i can't wait for the new feature get to the stable version on google play.
You really did a great job, i would not even mind if you'd put a small ad!

**Comment by Linkinverse** [comment]
Hello,

i just wanted to inform you that i have actually been using the version 1.1 you uploaded until now;
and i haven't found any bug or issue of any kind so far (i have software QA experience).

I hope you will upload it on F-Droid and Google Play very soon.
Thank you for your great work!

**Comment by EvanRespaut** [comment]
Yeah I will be doing that soon! There is actually one bug that I've since
fixed, landscape mode crashes the app. Ops. But yeah I should be done with
the tweaks soon and will be uploading in a few days.
