### ISSUE TITLE
Issue with speed covertion

### ISSUE THREAD

**Issue by wary-hermit** [EvanRespaut/Equate#53]
10 min/mi -> min/km gives 0.0621.... But expected result is 6.21.. 
For some reason both min/mi -> kph and min/km -> kph work correctly (10min/mi -> 9.656kph and 10min/km -> 6kph), but when trying to convert between them - wrong result is given.

**Comment by alerque** [comment]
For the record for anyone finding this issue or tracking this repository...

This does *not* seem to be fixed in the current version. I can still replicate it.
