### ISSUE TITLE
Long press functionnality ")" can cause a crash

### ISSUE THREAD

**Issue by geokie** [EvanRespaut/Equate#6]
When I type `(` + `1` + long press on `)`the app crash.
Output of the `adb logcat` command when the crash occurs: [Equate_crash_log.txt](https://github.com/EvanRespaut/Equate/files/223083/Equate_crash_log.txt)

Device: Nexus 5
OS: Cyanogenmod 13 (AOSP 6.0.1)
App version: 1.1 (downloaded via F-Droid)

**Comment by EvanRespaut** [comment]
Ahh good catch, I'll fix that with the next update.

**Comment by EvanRespaut** [comment]
Just put up an new version that will fix this crash.  Thanks for the catch.
