### ISSUE TITLE
[Feature request] Time conversion

### ISSUE THREAD

**Issue by davidak** [EvanRespaut/Equate#8]
For example seconds to days.

**Comment by alekksander** [comment]
Yes please.
In my case it's minutes to days.

**Comment by EvanRespaut** [comment]
Ok, I can add this next release :)

**Comment by alekksander** [comment]
Excellent!
Thank You for keeping this amazing application alive.

**Comment by EvanRespaut** [comment]
I just put up a new copy of Equate on the play store with time units.  Enjoy!
