### ISSUE TITLE
[Unit Request] Add pressure unit - centimetre of water

### ISSUE THREAD

**Issue by radioxoma** [EvanRespaut/Equate#9]
Please add [cm H<sub>2</sub>O](https://en.wikipedia.org/wiki/Centimetre_of_water) pressure unit. It used for evaluation of [central venous pressure](https://en.wikipedia.org/wiki/Central_venous_pressure) and [lung ventilator](https://en.wikipedia.org/wiki/Artificial_ventilation) setup. CVP is pretty easy to measure with ruler and plastic tube, filled with saline (NaCl in water), so cm H<sub>2</sub>O is used for it.

**Comment by EvanRespaut** [comment]
I can do that, it'll be in the next version.  I'll try to release it soon :)

**Comment by radioxoma** [comment]
Thanks! I'll be waiting on [F-droid](https://f-droid.org/repository/browse/?fdfilter=Equate&fdid=com.llamacorp.equate).

**Comment by EvanRespaut** [comment]
I just put up a new copy of Equate on the play store with cmH2O.  Looks like F-Droid automatically syncs with that so it should be up there too soon.  Enjoy!

**Comment by radioxoma** [comment]
Hm. I got v1.2 since [2016-11-30](https://f-droid.org/repository/browse/?fdfilter=Equate&fdid=com.llamacorp.equate) (F-Droid latest) and it has requested cmH<sub>2</sub>O. You had added unit at [25th Nov](https://github.com/EvanRespaut/Equate/commits/b719b57decfdfbbb3ac7cdfdfdf556a95e13bafd/app/src/main/AndroidManifest.xml) though. But on the Play store v1.3. Looks like F-Droid checks *AndroidManifest.xml* periodically and your commit triggered build.
Thank you for app. I'll change to playstore for a while and put you some stars :)

**Comment by EvanRespaut** [comment]
Yeah it looks like F-Droid is sometimes slow to grab updates from Play
Store. I'm not really sure how to force it to update, let me know if you
have an idea.  Thanks for the stars!

**Comment by radioxoma** [comment]
Just checked. Looks like you have to use git tags to specify the [release's](https://github.com/EvanRespaut/Equate/releases) versions and request to enable [Auto-update mode](https://f-droid.org/manual/html_node/Auto-Update-Mode.html). Auto-update is disabled: you can see it on [wiki page](https://f-droid.org/wiki/page/com.llamacorp.equate) and in [Metadata](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.llamacorp.equate.txt#L40) file.

Check this [post](https://f-droid.org/forums/topic/updating-my-app/#post-22907) on F-Droid forum.
